sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

before_install:
  - pip install pep8

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
# TODO: add flake8, pytest
script:
  - pep8 *.py
  - python -m py_compile *.py
  # - nosetests
